### ISSUE TITLE
inplace_abn.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bolongliu** [soon-yau/visconet#7]
ImportError: /home/.cache/torch_extensions/py38_cu113/inplace_abn/inplace_abn.so: cannot open shared object file: No such file or directory

How to solve this problem?

**Comment by soon-yau** [comment]
This looks like incompatible pytorch or cuda version. You should stick to pytorch=1.12.1 and find a cuda version that your GPU driver supports.
